owner: tenebrie # Your GitHub organization or username, where this repository lives
repo: neverkin-status # The name of this repository

sites:
  - name: Landing Page
    url: https://neverkin.com
  - name: App Frontend
    url: https://app.neverkin.com
  - name: Rest API
    url: https://app.neverkin.com/api/health
  - name: Websockets
    url: https://app.neverkin.com/calliope/health
  - name: MCP Server
    url: https://app.neverkin.com/orpheus/health
  - name: Landing Page (Staging)
    url: https://staging.neverkin.com
  - name: App Frontend (Staging)
    url: https://app.staging.neverkin.com
  - name: Rest API (Staging)
    url: https://app.staging.neverkin.com/api/health
  - name: Websockets (Staging)
    url: https://app.staging.neverkin.com/calliope/health
  - name: MCP Server (Staging)
    url: https://app.staging.neverkin.com/orpheus/health

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.neverkin.com
  # baseUrl: /neverkin-status
  logoUrl: https://raw.githubusercontent.com/Tenebrie/neverkin-status/HEAD/assets/neverkin-logo-dragon.webp
  favicon: https://raw.githubusercontent.com/Tenebrie/neverkin-status/HEAD/assets/favicon.ico
  name: Neverkin Status
  introTitle: "**Neverkin** Status"
  introMessage: This is the status page for [Neverkin](https://neverkin.com), the collaborative worldbuilding platform for writers, game masters, and creators. Organize timelines, characters, lore, and interconnected stories — all in real-time with your friends.
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: Neverkin
      href: https://neverkin.com
    - title: GitHub
      href: https://github.com/tenebrie/timelines
